### ISSUE TITLE
ModuleNotFoundError: No module named 'sc2.ids'

### ISSUE THREAD

**Issue by raimohanska** [Dentosal/python-sc2#1]
Did my best to follow the instructions and run an example and got this.

```
➜  python-sc2 git:(master) python3 examples/worker_rush.py
Traceback (most recent call last):
  File "examples/worker_rush.py", line 1, in <module>
    import sc2
  File "/Users/jpaanane/Library/Python/3.6/lib/python/site-packages/sc2/__init__.py", line 5, in <module>
    from .data import *
  File "/Users/jpaanane/Library/Python/3.6/lib/python/site-packages/sc2/data.py", line 9, in <module>
    from .ids.unit_typeid import PROBE, SCV, DRONE
ModuleNotFoundError: No module named 'sc2.ids'
```

**Comment by Dentosal** [comment]
Fixed by 7b5cc34
