### ISSUE TITLE
ERROR:sc2.main:AI step threw an error

### ISSUE THREAD

**Issue by naga456** [Dentosal/python-sc2#108]
I got the error message while playing against two bots.  The game loads and runs for about 4-5 mins.

Using TensorFlow backend.
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     AbyssalReefLE
INFO:sc2.controller:Players: Bot(Race.Terran, <jens_helper_bot_v01.JenshelperBot object at 0x000001D3B2C7A080>), Bot(Race.Protoss, <sc2_v06.SentdeBot object at 0x000001D3B50BD518>)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.in_game (was None)
INFO:root:Player id: 1
INFO:sc2.protocol:Client status changed to Status.in_game (was None)
INFO:root:Player id: 2
ERROR:sc2.bot_ai:Error: ActionResult.NotEnoughMinerals (action: UnitCommand(AbilityId.PROTOSSBUILD_ASSIMILATOR, Unit(name='Probe', tag=4351328257), Unit(name='VespeneGeyser', tag=4297064449), False))
ERROR:sc2.bot_ai:Error: ActionResult.NotEnoughMinerals (action: UnitCommand(AbilityId.PROTOSSBUILD_ASSIMILATOR, Unit(name='Probe', tag=4352114689), Unit(name='VespeneGeyser', tag=4297326593), False))
ERROR:sc2.bot_ai:Error: ActionResult.NotEnoughMinerals (action: UnitCommand(AbilityId.NEXUSTRAIN_PROBE, Unit(name='Nexus', tag=4349755393), None, False))
ERROR:sc2.bot_ai:Error: ActionResult.NotEnoughMinerals (action: UnitCommand(AbilityId.PROTOSSBUILD_GATEWAY, Unit(name='Probe', tag=4351066113), (34, 122), False))
ERROR:sc2.bot_ai:Error: ActionResult.NotEnoughMinerals (action: UnitCommand(AbilityId.PROTOSSBUILD_NEXUS, Unit(name='Probe', tag=4351328257), (65, 113), False))
ERROR:sc2.main:AI step threw an error
Traceback (most recent call last):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 56, in _play_game_ai
    await ai.on_step(iteration)
  File "C:\Users\wl030\Desktop\Python\sc2\jens_helper_bot_v01.py", line 16, in on_step
    cc = cc.first
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\units.py", line 68, in first
    assert self.exists
AssertionError
ERROR:sc2.main:resigning due to previous error
INFO:root:Result for player id: 1: Result.Defeat
INFO:sc2.protocol:Client status changed to Status.launched (was Status.in_game)
INFO:sc2.protocol:Client status changed to Status.quit (was Status.launched)
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
ERROR:sc2.protocol:Cannot receive: Connection already closed.
Traceback (most recent call last):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 34, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\aiohttp\client_ws.py", line 254, in receive_bytes
    msg.data))
TypeError: Received message 257:None is not bytes
ERROR:sc2.main:AI step threw an error
Traceback (most recent call last):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 34, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\aiohttp\client_ws.py", line 254, in receive_bytes
    msg.data))
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 56, in _play_game_ai
    await ai.on_step(iteration)
  File "C:\Users\wl030\Desktop\Python\sc2\sc2_v06.py", line 45, in on_step
    await self.build_pylons()
  File "C:\Users\wl030\Desktop\Python\sc2\sc2_v06.py", line 203, in build_pylons
    await self.build(PYLON, near=nexuses.first)
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\bot_ai.py", line 370, in build
    p = await self.find_placement(building, near.rounded, max_distance, random_alternative, placement_step)
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\bot_ai.py", line 294, in find_placement
    if await self.can_place(building, near):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\bot_ai.py", line 279, in can_place
    r = await self._client.query_building_placement(building, [position])
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\client.py", line 206, in query_building_placement
    ignore_resource_requirements=ignore_resources
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 47, in _execute
    response = await self.__request(request)
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 37, in __request
    raise ConnectionAlreadyClosed("Connection already closed.")
sc2.protocol.ConnectionAlreadyClosed: Connection already closed.
ERROR:sc2.main:resigning due to previous error
INFO:root:Result for player id: 2: Result.Defeat
WARNING:aiohttp.websocket:websocket connection is closing.
ERROR:sc2.protocol:Cannot receive: Connection already closed.
Traceback (most recent call last):
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 34, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\wl030\AppData\Roaming\Python\Python36\site-packages\aiohttp\client_ws.py", line 254, in receive_bytes
    msg.data))
TypeError: Received message 257:None is not bytes
ERROR:root:Connection was closed before the game ended
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D3BA672EF0>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D3BA6A5AC8>

**Comment by naga456** [comment]
Close as code logic error.
