### ISSUE TITLE
expand_now() not working properly

### ISSUE THREAD

**Issue by ByBurton** [Dentosal/python-sc2#113]
I have this code here: 
	async def expand(self):
		if self.can_afford(HATCHERY) and not self.already_pending(HATCHERY):
			await self.chat_send('trying to expand')
			await self.expand_now()

The first expansion works perfectly. But whenever it should do the second expansion, the script crashes.
The error I get: 
ERROR:sc2.main:AI step threw an error
Traceback (most recent call last):
  File "E:\Program Files\Python37\lib\site-packages\sc2\main.py", line 61, in _play_game_ai
    await ai.on_step(iteration)
  File "E:\Downloads\python-sc2-master\own bot tests\HiveMind.py", line 15, in on_step
    await self.expand()
  File "E:\Downloads\python-sc2-master\own bot tests\HiveMind.py", line 224, in expand
    await self.expand_now()
  File "E:\Program Files\Python37\lib\site-packages\sc2\bot_ai.py", line 114, in expand_now
    await self.build(building, near=location, max_distance=max_distance, random_alternative=False, placement_step=1)
  File "E:\Program Files\Python37\lib\site-packages\sc2\bot_ai.py", line 370, in build
    p = await self.find_placement(building, near.rounded, max_distance, random_alternative, placement_step)
  File "E:\Program Files\Python37\lib\site-packages\sc2\bot_ai.py", line 286, in find_placement
    assert self.can_afford(building)
AssertionError
ERROR:sc2.main:resigning due to previous error
INFO:root:Result for player id: 1: Result.Defeat

Or is it an error I made? If so, please, tell me!
~Kimberly

**Comment by BurnySc2** [comment]
Duplicate https://github.com/Dentosal/python-sc2/issues/97

**Comment by BurnySc2** [comment]
It should be fixed now and on master branch. If you still encounter issues, feel free to reopen this issue.
