### ISSUE TITLE
Error starting up game: "TypeError: object NoneType can't be used in 'await' expression"

### ISSUE THREAD

**Issue by ericbroda** [Dentosal/python-sc2#131]
I am using the code in the current master branch and have tried both Python version 3.6 and 3.7 (on MacOS)... both versions of Python cause this error when I upgraded to the current master branch (I successfully was using an older version)

Below is the information from the console:

err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.4.5/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:244
err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.4.5/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:258
err = 3 /opt/blizzard/buildserver/data.noindex/repositories/sc2/branches/SC2.4.5/Game/Contrib/macteam/libs/ClampCursor/Contrib/mach_override/mach_override.c:263
NSWindowEdgeResizing is off!
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     AbyssalReefLE
INFO:sc2.controller:Players: Bot(Race.Protoss, <qbot.QBot object at 0x1077ec860>), Computer(Race.Terran, Difficulty.Easy)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.in_game (was None)
INFO:root:Player id: 1
ERROR:sc2.main:AI step threw an error
Traceback (most recent call last):
  File "[MY-PATH]/sc2/main.py", line 56, in _play_game_ai
    await ai.issue_events()
TypeError: object NoneType can't be used in 'await' expression
ERROR:sc2.main:resigning due to previous error
INFO:root:Result for player id: 1: Result.Defeat
INFO:sc2.protocol:Client status changed to Status.launched (was Status.in_game)
INFO:sc2.protocol:Client status changed to Status.quit (was Status.launched)
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete

**Comment by BurnySc2** [comment]
Did you edit the `issue_events` function in your bot?
Or maybe you updated the `main.py` file but not the `bot_ai.py` file?

**Comment by ericbroda** [comment]
I tried out using the current master source code and that is when the problem occurred.  I reverted to the previous stable release (0.9.0) and it was fixed.  I was unable to debug it so unfortunately I cannot give you more information.  However, the good news is that I am running OK again with the previous release.

**Comment by thommath** [comment]
It looks like it's a bug introduced when the events started getting issued async. I'm looking into it

**Comment by thommath** [comment]
I'm getting the same error, but on_building_complete instead. When I include the await i get the error[0] and when I remove it I get warning that the function isn't awaited[1]. I've looked around, but unable to find what causes it. If I revert back to a non-async version it works great, but I guess that's a step in the wrong direction...

[0]: `ERROR:sc2.main:AI step threw an error                                                                                   Traceback (most recent call last):                                                                                        File "C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\site-packages\sc2\main.py", line 56, in _play_game_ai     await ai.issue_events()                                                                                               File "C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\site-packages\sc2\bot_ai.py", line 470, in issue_events                                                                                                                           await self._issue_building_complete_event(unit)                                                                       File "C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\site-packages\sc2\bot_ai.py", line 484, in _issue_building_complete_event                                                                                                         await self.on_building_construction_complete(unit)                                                                  TypeError: object NoneType can't be used in 'await' expression`

[1]: `C:\Users\thoma\AppData\Local\Programs\Python\Python37\lib\site-packages\sc2\bot_ai.py:484: RuntimeWarning: coroutine 'BotAI.on_building_construction_complete' was never awaited                                                                  self.on_building_construction_complete(unit)`

**Comment by BurnySc2** [comment]
How can I reproduce this error?
Do the example bots work for you?
Does the error only appear when you start using the event functions? Could you give me a small example so I can reproduce it?

**Comment by theadamcraig** [comment]
Also on a Mac with python 3.6.5

```
ERROR:sc2.main:AI step threw an error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sc2/main.py", line 56, in _play_game_ai
    await ai.issue_events()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sc2/bot_ai.py", line 503, in issue_events
    await self._issue_unit_added_events()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sc2/bot_ai.py", line 510, in _issue_unit_added_events
    await self.on_unit_created(unit)
TypeError: object NoneType can't be used in 'await' expression
ERROR:sc2.main:resigning due to previous error
```

I overwrote the function with this:
```	def on_unit_created(self, unit):
		""" Override this in your bot class
		if a unit is a phoenix. add it to the list of units 
		to check if they are a hallucination."""
		if unit.type_id == UnitTypeId.PHOENIX:
			self.units_to_check.append(unit.tag)
			log('Adding Phoenix to Check List')
```

I commented out the entire function and it runs without crashing.

but if I do this:
```	def on_unit_created(self, unit):
#		""" Override this in your bot class
#		if a unit is a phoenix. add it to the list of units 
#		to check if they are a hallucination."""
#		if unit.type_id == UnitTypeId.PHOENIX:
#			self.units_to_check.append(unit.tag)
#			log('Adding Phoenix to Check List')
		pass
```

it crashes again.

**Comment by ericbroda** [comment]
Newest version seems to fix the issue
