### ISSUE TITLE
Cannot import sc2 - dll error

### ISSUE THREAD

**Issue by HayJayDee** [Dentosal/python-sc2#183]
Hi I am new to sc2 and I installed it tried to just import sc2 and got this error in my python idle
Traceback (most recent call last):
  File "M:\Python36\Lib\site-packages\examples\protoss\cannon_rush.py", line 3, in <module>
    import sc2
  File "M:\Python36\lib\site-packages\sc2\__init__.py", line 18, in <module>
    from .data import *
  File "M:\Python36\lib\site-packages\sc2\data.py", line 2, in <module>
    from s2clientprotocol import (
  File "M:\Python36\lib\site-packages\s2clientprotocol\sc2api_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "M:\Python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
what went wrong i dont know :(

**Comment by HayJayDee** [comment]
sry it is german but i hope you can read it :)

**Comment by HayJayDee** [comment]
and I also tryed to reinstall sc2 and starcraft 2 nothing worked.
I use python 3.6

**Comment by Dentosal** [comment]
You need to upgrade your Python to 3.6.1 or 3.7. Found solution in [this issue](https://github.com/NordicSemiconductor/pc-nrfutil/issues/133).
