### ISSUE TITLE
Trying to run worker rush returns "sc2.protocol.ProtocolError: ['A game has not been started yet']"

### ISSUE THREAD

**Issue by XanthanGum** [Dentosal/python-sc2#52]
Hi,

I'm trying to run the worker rush example and get this error. Happens with all other example bots I try. Happens when I try different maps too.Not sure myself what the error means.

PS C:\Users\Matt\Google Drive\Python\Starcraft 2> python QuilBot.py
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     FrostLE
INFO:sc2.controller:Players: Bot(Race.Zerg, <__main__.WorkerRushBot object at 0x000001B4D79AEF98>), Computer(Race.Protoss, Di

fficulty.Medium)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:root:Player id: 0
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "QuilBot.py", line 16, in <module>
    ], realtime=True)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Users\Matt\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 115, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 87, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 29, in _play_game_ai
    game_data = await client.get_game_data()
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\client.py", line 110, in get_game_data
    upgrade_id=True
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 56, in _execute
    raise ProtocolError(f"{response.error}")
sc2.protocol.ProtocolError: ['A game has not been started yet']

Any help appreciated. Thanks.

**Comment by WanklordJimmy** [comment]
I Have exactly the same problem. I run the script, starcraft tries to start up for 2s, but crashes every time with every script ive tried. 
I tired with spyder(anaconda py.3.6) and just plain py3.6. Neither of them worked.

**Comment by Prometheus3D** [comment]
I too am getting the same issue:

"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\python.exe" "D:/AI Project/StarCraft2_bot/scBot.py"
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game
INFO:sc2.controller:Map:     CactusValleyLE
INFO:sc2.controller:Players: Bot(Race.Terran, <__main__.SC2Bot object at 0x0000020D5D161EB8>), Computer(Race.Terran, Difficulty.Easy)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:root:Player id: 0
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
Traceback (most recent call last):
INFO:sc2.sc2process:Cleanup complete
  File "D:/AI Project/StarCraft2_bot/scBot.py", line 16, in <module>
    ], realtime=True)
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\main.py", line 115, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\main.py", line 87, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\main.py", line 29, in _play_game_ai
    game_data = await client.get_game_data()
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\client.py", line 110, in get_game_data
    upgrade_id=True
  File "D:\AI Project\StarCraft2_bot\python-sc2\sc2\protocol.py", line 56, in _execute
    raise ProtocolError(f"{response.error}")
sc2.protocol.ProtocolError: ['A game has not been started yet']

**Comment by BurnySc2** [comment]
It might be a stupid guess and bad suggestion, but you both have Python installed at locations with spaces in their folder names. A friend of mine had that too, I suggested him to reinstall to some simple folder path, e.g. 
```
C:\Python36\
```
and it suddenly worked for him. He also got a long error about `Connect call failed`.
For him, it might have been either the spaces in the folder name or he installed it somewhere where he didn't have admin rights.

**Comment by XanthanGum** [comment]
Thanks for the advice. Reinstalled python and tried again but still returns the same error.

PS C:\Users\Matt\Google Drive\Python\Starcraft 2> python QuilBot.py
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:sc2.controller:Creating new game

INFO:sc2.controller:Map:     FrostLE
INFO:sc2.controller:Players: Bot(Race.Zerg, <__main__.WorkerRushBot object at 0x044FBFB0>), Computer(Race.Protoss, Difficulty
.Medium)
INFO:sc2.protocol:Client status changed to Status.init_game (was Status.launched)
INFO:sc2.protocol:Client status changed to Status.launched (was None)
INFO:root:Player id: 0
INFO:sc2.sc2process:kill_switch: Process cleanup
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "QuilBot.py", line 16, in <module>
    ], realtime=True)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\python36\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 115, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 87, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\main.py", line 29, in _play_game_ai
    game_data = await client.get_game_data()
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\client.py", line 110, in get_game_data
    upgrade_id=True
  File "C:\Users\Matt\AppData\Roaming\Python\Python36\site-packages\sc2\protocol.py", line 56, in _execute
    raise ProtocolError(f"{response.error}")
sc2.protocol.ProtocolError: ['A game has not been started yet']

**Comment by bnvl** [comment]
Had the exact same problem, so my solution may help you as well.

The issue that caused this error for me was that the map the bot was trying to load was in fact corrupted, which led to the game instance crashing at startup.

If you had downloaded the map packs from the official API, you have to make sure they were properly extracted - the zip files are password protected. You can find the password under the Downloads section on this page - [Blizzard/s2client-proto](https://github.com/Blizzard/s2client-proto#downloads).

Hope this helps.

**Comment by XanthanGum** [comment]
Thanks mate. That was exactly the problem for me.

**Comment by mydhui** [comment]
Thanks for bnvl's comment, I solve this problem by correctly typing password while extracting those map zip files (If you don't type password, it'll just let you extract map files, but it mean you didn't accept the protocol). Don't forget the protocol.  - [Blizzard/s2client-proto](https://github.com/Blizzard/s2client-proto#downloads)

**Comment by JulianGmp** [comment]
I don't have anything productive to say but HOW ON EARTH DOES THE MAP JUST CORRUPT.

WE SPENT AN ENTIRE WEEK TRYING TO FIX THIS.

AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
