### ISSUE TITLE
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited

### ISSUE THREAD

**Issue by DannyMatar** [Dentosal/python-sc2#67]
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "C:\Users\matar\Documents\GitHub\AI-SC2-Python\AI_SC2_Python.py", line 14, in <module>
    ], realtime=True)
  File "C:\Users\matar\AppData\Roaming\Python\Python37\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\matar\AppData\Roaming\Python\Python37\site-packages\sc2\main.py", line 109, in _host_game
    async with SC2Process() as server:
  File "C:\Users\matar\AppData\Roaming\Python\Python37\site-packages\sc2\sc2process.py", line 57, in __aenter__
    self._ws = await self._connect()
  File "C:\Users\matar\AppData\Roaming\Python\Python37\site-packages\sc2\sc2process.py", line 99, in _connect
    ws = await websockets.connect(self.ws_url, timeout=120)
  File "C:\Users\matar\AppData\Roaming\Python\Python37\site-packages\websockets\client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
[Finished in 3.9s with exit code 1]

**Comment by DannyMatar** [comment]
#65 Has a solution, which worked for me.

Solution:
Downgrade Python from 3.7 to 3.6.6
