### ISSUE TITLE
Server/Client Error w/ Fresh install of sc2 and Python 3.7

### ISSUE THREAD

**Issue by nosbor2001** [Dentosal/python-sc2#76]
This is the error I get when running an example .py with a fresh install of Python 3.7 and sc2.

A firewall message did appear and I clicked allow access and since the error is coming from the server and client .py's I am assuming it has something to do with this. Tried to build in both Sublime Text and IDLE but to no avail.

```
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "C:\Users\drewr\Desktop\Python Projects\Starcraft 2 Bot\bot.py", line 131, in <module>
    ], realtime=False)
  File "C:\Users\drewr\AppData\Roaming\Python\Python37\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\drewr\AppData\Roaming\Python\Python37\site-packages\sc2\main.py", line 109, in _host_game
    async with SC2Process() as server:
  File "C:\Users\drewr\AppData\Roaming\Python\Python37\site-packages\sc2\sc2process.py", line 57, in __aenter__
    self._ws = await self._connect()
  File "C:\Users\drewr\AppData\Roaming\Python\Python37\site-packages\sc2\sc2process.py", line 99, in _connect
    ws = await websockets.connect(self.ws_url, timeout=120)
  File "C:\Users\drewr\AppData\Roaming\Python\Python37\site-packages\websockets\client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
[Finished in 4.1s]
```

**Comment by nosbor2001** [comment]
Found out this issue was a duplicate issue highlighted in issue #65 with the cause of the problem looking like an update problem when installing new pythons, my best guess. However, the solution shown hasn't been of any use to me as it still throws this error. Might try downgrading python.

**Comment by nosbor2001** [comment]
Weird Issue, obviously something to do with python 3.7 as 3.6.6 works fine
