### ISSUE TITLE
package doesn't work on python 3.7.0

### ISSUE THREAD

**Issue by Garakros** [Dentosal/python-sc2#78]
## Minimal reproduce

```python
import sc2
from sc2 import run_game, maps, Race, Difficulty
from sc2.player import Bot, Computer


class Bot(sc2.BotAI):
    async def on_step(self, iteration):
        # what to do every step
        await self.distribute_workers()  # in sc2/bot_ai.py


run_game(
    maps.get("AbyssalReefLE"), [
        Bot(Race.Protoss, Bot()),
        Computer(Race.Terran, Difficulty.Easy)
    ],
    realtime=True
)
```

Gives Error:

```
INFO:sc2.sc2process:Cleaning up...
INFO:sc2.sc2process:Cleanup complete
Traceback (most recent call last):
  File "D:/sc2ai.py", line 10, in <module>
    run_game(maps.get("AbyssalReefLE"), [Bot(Race.Protoss, SentdeBot()), Computer(Race.Terran, Difficulty.Easy)], realtime=True)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sc2\main.py", line 187, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sc2\main.py", line 109, in _host_game
    async with SC2Process() as server:
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sc2\sc2process.py", line 57, in __aenter__
    self._ws = await self._connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sc2\sc2process.py", line 99, in _connect
    ws = await websockets.connect(self.ws_url, timeout=120)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\websockets\client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
```

**Comment by itzclay** [comment]
I had the exact same error.     I know he's aware of the issue because I messaged him on reddit about it, but he was too busy to address it.   

I just ended up installing 3.6 and it worked fine then.

**Comment by nosbor2001** [comment]
It's something to do with a change in websockets I believe between the versions

**Comment by BurnySc2** [comment]
Is it working now for Python 3.7 since this commit? https://github.com/Dentosal/python-sc2/commit/b23210caec78ed585ecd0504dc73e3e70828f901

**Comment by itzclay** [comment]
Haven't tried it, but looking at the code changes it looks like websockets has been replaced so my guess is yes.

**Comment by Dentosal** [comment]
Fixed previously. Please open a new issue if you find bugs with Python 3.7
