### ISSUE TITLE
MAPS ERROR

### ISSUE THREAD

**Issue by BlaQBobby** [Dentosal/python-sc2#81]
So I downloaded all of the maps (I'm using python 3.5) and extracted them ALL in the StarCraftII/Maps folder. I also set my system SC2PATH properly to point to the super-folder that holds the StarCraftII folder. When I try to run, I get the errors below. I've traced this to no avail
`Traceback (most recent call last):
  File "simpleBot.py", line 1, in <module>
    import sc2
  File "/home/blaq/miniconda2/envs/blaqPython35/lib/python3.5/site-packages/sc2/__init__.py", line 16, in <module>
    from . import maps
  File "/home/blaq/miniconda2/envs/blaqPython35/lib/python3.5/site-packages/sc2/maps.py", line 24
    raise KeyError(f"Map '{name}' was not found. Please put the map file in \"/StarCraft II/Maps/\".")
SyntaxError: invalid syntax
`

Notice that the Trace is coming from attempting to initialize the Maps, and as a result I think this is not about calling the right Map or not.
Please some help would be appreciate. See code I attempted to run below:

`import sc2
from sc2 import run_game, maps, Race, Difficulty
from sc2.player import Bot, Computer

class WorkerRushBot(sc2.BotAI):
    async def on_step(self, iteration):
        if iteration == 0:
            for worker in self.workers:
                await self.do(worker.attack(self.enemy_start_locations[0]))

run_game(maps.get("Abyssal Reef LE"), [
    Bot(Race.Zerg, WorkerRushBot()),
    Computer(Race.Protoss, Difficulty.Medium)
], realtime=True)`

**Comment by BlaQBobby** [comment]
Update:
Issue was with the f-string formatting not being compatible with python 3.5
Thanks.
