### ISSUE TITLE
Game crashes when map doesn't have limits

### ISSUE THREAD

**Issue by NikEyX** [Dentosal/python-sc2#86]
The problem is in ```_pxmap_sub_scale``` within maps.py. If ```(limits[1] - limits[0])``` is zero, the game gets an integer division by zero error.

FIX: Just check that ```(limits[1] - limits[0]) != 0 ``` near line 23 of maps.py

Traceback (most recent call last):
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\main.py", line 147, in run_game
    _host_game(map_settings, players, **kwargs)
  File "C:\Anaconda\envs\py36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\main.py", line 108, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\main.py", line 84, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\main.py", line 30, in _play_game_ai
    game_info = await client.get_game_info()
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\client.py", line 111, in get_game_info
    return GameInfo(result.game_info)
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\game_info.py", line 38, in __init__
    self.map_ramps = _pxmap_sub_scale(self.pathing_grid, self.placement_grid, self.terrain_height)
  File "C:\Anaconda\envs\py36\lib\site-packages\sc2-0.7.9-py3.6.egg\sc2\game_info.py", line 23, in _pxmap_sub_scale
    scaled = int((map3[(x, y)] - limits[0]) * 255) // (limits[1] - limits[0])
ZeroDivisionError: integer division or modulo by zero

**Comment by Dentosal** [comment]
I think this was fixed in v0.8.0.
